### ISSUE TITLE
AMMWithraw tfWithdrawAll flag seems to be in the wrong category

### ISSUE THREAD

**Issue by JST5000** [ripple/opensource.ripple.com#55]
https://opensource.ripple.com/docs/xls-30d-amm/transaction-types/ammwithdraw/

![image](https://github.com/ripple/opensource.ripple.com/assets/19694186/4a76b963-d12d-4843-a2e2-503d52e384e0)

I was confused reading how to use `tfWithdrawAll` at first since I thought I needed to specify both fields since it was in the "Double field" cateogry, yet it says to specify no fields. I think `tfWithdrawAll` should be in a third category of "No Fields" which would cause an update to wording above the tables.

**Comment by mDuo13** [comment]
No, the categories are not defined based on which fields you specify. In fact, every flag requires different fields, which is why there's a "Fields Specified" column in the table.

The difference is, as mentioned into the bullet points above, whether you receive two assets or one and whether you pay a fee. tfWithdrawAll is correctly categorized.
